---
language: php

addons:
  apt:
    packages:
    - elinks # For dysplaying php files on console.
    - colordiff

cache:
  directories:
  - $HOME/.composer/cache/files

php:
- nightly
- 7.2
- 7.1
- 7.0

env:
  global:
  - COMPOSER_BIN_DIR=bin
  # - COMPOSER=composer-dev.json # https://travis-ci.org/symfony-flex-demo/env-COMPOSER-and-symfony.lock
  # - PATH=$TRAVIS_BUILD_DIR/bin::$PATH

matrix:
  fast_finish: true
  allow_failures:
  - php: nightly

before_install:
- go get -u github.com/jingweno/ccat
# Disabling Xdebug - Debugger and Profiler Tool for PHP
- |
  php -r "print_r(get_loaded_extensions(TRUE));"
  if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
    cat ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    install --directory ~/.phpenv/versions/$(phpenv version-name)/etc/on-demand
    mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ~/.phpenv/versions/$(phpenv version-name)/etc/on-demand
    php -r "print_r(get_loaded_extensions(TRUE));"
  fi

install:
- |
  mv composer.json composer-orig.json
  mv composer-skeleton.json composer.json
  pushd config/packages
  mv easy_admin.yaml .easy_admin.yaml
  popd
  # composer create-project symfony/skeleton
  # cd skeleton
  composer require symfony/flex
  composer require symfony/yaml
  composer require symfony/dotenv --dev
  composer require symfony/console
  composer require symfony/framework-bundle
  composer require friendsofsymfony/ckeditor-bundle
  composer require symfony/orm-pack
  pushd config/packages
  mv .easy_admin.yaml easy_admin.yaml
  popd
  composer require easycorp/easyadmin-bundle
  composer require symfony/profiler-pack --dev
  composer require symfony/web-server-bundle --dev
  composer initialize # -- --ansi
  # composer exec -- console doctrine:database:create
  # composer exec -- console doctrine:migrations:diff --quiet
  # composer exec -- console doctrine:migrations:migrate --no-interaction --quiet
  # composer exec -- console ckeditor:install --quiet
  # composer exec -- console assets:install  --symlink --relative

script:
- true

after_script:
- ls --almost-all --color
- cat .env
- cat .env.dist
- ls --color bin
- ls --almost-all --recursive --color var
- ls --color src
- ls --color src/Controller
- ls --color src/Entity
- php -s src/Entity/Author.php | elinks -force-html -dump-color-mode 4 -dump
- php -s src/Entity/BlogPost.php | elinks -force-html -dump-color-mode 4 -dump
- ls --color src/Repository
- php -s src/Repository/AuthorRepository.php | elinks -force-html -dump-color-mode 4 -dump
- php -s src/Repository/BlogPostRepository.php | elinks -force-html -dump-color-mode 4 -dump
- composer exec --verbose -- console doctrine:query:sql "INSERT INTO author (name) VALUES ('Tom B. Erichsen')"
- composer exec --verbose -- console doctrine:query:dql "SELECT a FROM App\Entity\Author a"
- composer exec --verbose -- console doctrine:query:sql "SELECT * FROM author"
- ls --recursive --color config
- $GOPATH/bin/ccat config/packages/doctrine.yaml
- $GOPATH/bin/ccat config/packages/easy_admin.yaml
- $GOPATH/bin/ccat config/packages/ivory_ck_editor.yaml ######################################################3
- $GOPATH/bin/ccat config/routes/easy_admin.yaml

- composer exec --verbose -- console debug:router
# - composer exec --verbose -- console server:start # console server:start blocks endlessly with composer exec
- bin/console server:start
- printf 'HEAD /admin/ HTTP/1.1\r\n\r\n' | socat - TCP4:localhost:8000,forever >/dev/null # Waiting for server to connect.
- elinks http://localhost:8000/admin -dump-color-mode 4 -dump
# - elinks http://localhost:8000/index.php/admin -dump-color-mode 4 -dump


- composer show --latest
- $GOPATH/bin/ccat composer-orig.json
- $GOPATH/bin/ccat composer.json
- diff --help
# - diff --minimal --side-by-side --color composer-dev.json composer.json needs a Ubuntu version newer than Trusty
- colordiff --minimal --side-by-side composer-orig.json composer.json

- composer exec --list --ansi
- composer run-script --list --ansi
- composer exec --verbose -- console --ansi

- composer exec --verbose -- console list debug --ansi
- composer exec --verbose -- console help debug:router --ansi

- composer exec --verbose -- console list doctrine --ansi
- composer exec --verbose -- console help doctrine:database:create --ansi
# - composer exec --verbose -- console help doctrine:generate:entities --ansi
- composer exec --verbose -- console help doctrine:mapping:convert --ansi
- composer exec --verbose -- console help doctrine:mapping:import --ansi
- composer exec --verbose -- console help doctrine:mapping:info --ansi
- composer exec --verbose -- console help doctrine:migrations:diff --ansi
- composer exec --verbose -- console help doctrine:migrations:migrate --ansi
- composer exec --verbose -- console help doctrine:query:dql --ansi
- composer exec --verbose -- console help doctrine:query:sql --ansi
- composer exec --verbose -- console help doctrine:schema:validate --ansi

- composer exec --verbose -- console list make --ansi
- composer exec --verbose -- console help make:crud --ansi
- composer exec --verbose -- console help make:entity --ansi
- composer exec --verbose -- console help make:migration --ansi

- composer exec --verbose -- console list ckeditor --ansi
- composer exec --verbose -- console help ckeditor:install --ansi

- composer exec --verbose -- console list router --ansi
- composer exec --verbose -- console help router:match --ansi

- composer exec --verbose -- console list server --ansi
- composer exec --verbose -- console help server:start --ansi
